name: workflow learning
on: workflow_dispatch
jobs:
  first:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout
        uses: actions/checkout@v3
  deploy: 
    runs-on: ubuntu-latest
    needs: first
    steps: 
      - name: say bruh
        run: echo "bruh"
